---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Examples of Plotly

Loading the libraries

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```


Load the Airbnb NYC data

```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500) %>% 
  drop_na(rating)
```

## Plotly plots

# Scatterplot

```{r}
nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```

## Boxplot

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

## Barchart

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

## ggplotly

You can convert a ggplot object straight to an interactive graphic using ggplotly. Not recommended though.

```{r}
scatter_ggplot = 
  nyc_airbnb %>%
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()

ggplotly(scatter_ggplot)
```

We can recreate our boxplot in a similar way:

```{r}
box_ggplot = 
  nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  ggplot(aes(x = neighbourhood, y = price, fill = neighbourhood)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(box_ggplot)
```

